services:
  app:
    build: .
    restart: always
    env_file:
      - .env
    depends_on:
      - mongodb
    networks:
      - focus_network

  mongodb:
    image: mongo:latest
    restart: always
    volumes:
      - mongodb_data:/data/db
    networks:
      - focus_network

networks:
  focus_network:
    driver: bridge

volumes:
  mongodb_data:
