services:
  app:
    build: .
    restart: always
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://mongodb:27017/focus_adhd
      - EVOLUTION_API_URL=https://evo.meuchatinteligente.com.br
      - EVOLUTION_API_KEY=${EVOLUTION_API_KEY}  # Certifique-se de que isso est치 definido no EasyPanel
      - EVOLUTION_INSTANCE=desafio
      - OPENAI_API_KEY=${OPENAI_API_KEY}  # Certifique-se de que isso est치 definido no EasyPanel
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}  # Certifique-se de que isso est치 definido no EasyPanel
      - STRIPE_WEBHOOK_SECRET=${STRIPE_WEBHOOK_SECRET}  # Certifique-se de que isso est치 definido no EasyPanel
      - PLAN_MONTHLY_PRICE=9900
      - PLAN_YEARLY_PRICE=99900
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    restart: always
    volumes:
      - mongodb_data:/data/db

  webhook-logger:
    image: node:18-alpine
    working_dir: /app
    volumes:
      - ./webhook-logger:/app
    command: ["node", "server.js"]

volumes:
  mongodb_data: